[package]
name = "debra"
description = "distributed epoch-based reclamation"
version = "0.1.0"
authors = ["Oliver Giersch"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/oliver-giersch/debra"
edition = "2018"

[dependencies]
arrayvec = "0.4.10"
reclaim = { git = "https://github.com/oliver-giersch/reclaim" }
